insert into palabras(espanol,japones)
values("ir","いきます"),("venir","きます"),("yo","わたし"),("tu","あなた"),("Maestro","せんせい"),("Maestro","きょうし"),("Estudiante","がくせい")
    ,("Estudiante","がくせい"),("Empleado","かいしゃいん"),("Medico","いしゃ"),("Investigador","けんきゅうしゃ"),("Universidad","だいがく"),
    ("Hospital","びょういん"),("Quien","だれ"),("Quien","どなた"),("Si","はい"),("No","いいえ"),("Este","これ"),("Esta","これ"),("Esto","これ"),
    ("Eso","それ"),("Esa","それ"),("Ese","それ"),("Aquello","あれ"),("Aquel","あれ"),("Aquella","あれ"),("Este","この"),("Esta","この"),("Ese","その"),("Esa","その"),
    ("Aquel","あの"),("Aquella","あの"),("libro","ほん"),("Diccionario","じしょ"),("Revista","ざっち"),("Periodico","しんふん"),("Diario","しんふん"),("Agenda","てちょう"),
    ("Tarjeta de presentacion","めいし"),("Lapiz","えんぴつ"),("llave","かぎ"),("reloj","とけい"),("Paraguas","かさ"),("bolso","かばん"),("auto","くるま"),
    ("automovil","くるま"),("Escritorio","つくえ"),("Silla","いす"),("Aqui","ここ"),("Ahi","そこ"),("Alla","あそこ"),("Donde","どこ"),("Aula","きょしつ"),("Sala de clases","きょしつ"),
    ("Comedor","しょくどう"),("Oficina","じむしょ"),("Sala de reuniones","かいぎしつ"),("Recepcion","うけつけ"),("Habitacion","へや"),("Cuarto","へや"),
    ("Baño","おてあらい"),("Escaleras","かいだん"),("Telefono","でんわ"),("Empresa","かｙしゃ"),("Casa","うち"),("Zapatos","くつ"),("Zapato","くつ"),("Sotano","ちか")


